SET GOPATH=%CD%
CD src\americanise & go build & CD %GOPATH%
CD src\apachereport1 & go build & CD %GOPATH%
CD src\apachereport2 & go build & CD %GOPATH%
CD src\apachereport3 & go build & CD %GOPATH%
CD src\apachereport4 & go build & CD %GOPATH%
CD src\apachereport5 & go build & CD %GOPATH%
CD src\archive_file_list & go build & CD %GOPATH%
CD src\archive_file_list_ans & go build & CD %GOPATH%
CD src\bigdigits & go build & CD %GOPATH%
CD src\bigdigits_ans & go build & CD %GOPATH%
CD src\cgrep1 & go build & CD %GOPATH%
CD src\cgrep2 & go build & CD %GOPATH%
CD src\cgrep3 & go build & CD %GOPATH%
CD src\chap4_ans & go build & CD %GOPATH%
CD src\common_prefix & go build & CD %GOPATH%
CD src\contains & go build & CD %GOPATH%
CD src\filter & go build & CD %GOPATH%
CD src\findduplicates & go build & CD %GOPATH%
CD src\font & go build & CD %GOPATH%
CD src\fuzzy & go build & CD %GOPATH%
CD src\fuzzy_immutable & go build & CD %GOPATH%
CD src\fuzzy_mutable & go build & CD %GOPATH%
CD src\fuzzy_value & go build & CD %GOPATH%
CD src\guess_separator & go build & CD %GOPATH%
CD src\hello & go build & CD %GOPATH%
CD src\imagetag1 & go build & CD %GOPATH%
CD src\imagetag2 & go build & CD %GOPATH%
CD src\indent_sort & go build & CD %GOPATH%
CD src\invoicedata & go build & CD %GOPATH%
CD src\invoicedata_ans & go build & CD %GOPATH%
CD src\linkcheck & go build & CD %GOPATH%
CD src\m3u2pls & go build & CD %GOPATH%
CD src\memoize & go build & CD %GOPATH%
CD src\ordered_map & go build & CD %GOPATH%
CD src\pack & go build & CD %GOPATH%
CD src\palindrome & go build & CD %GOPATH%
CD src\palindrome_ans & go build & CD %GOPATH%
CD src\pi_by_digits & go build & CD %GOPATH%
CD src\playlist & go build & CD %GOPATH%
CD src\polar2cartesian & go build & CD %GOPATH%
CD src\quadratic_ans1 & go build & CD %GOPATH%
CD src\quadratic_ans2 & go build & CD %GOPATH%
CD src\safemap & go build & CD %GOPATH%
CD src\safeslice & go build & CD %GOPATH%
CD src\shaper1 & go build & CD %GOPATH%
CD src\shaper2 & go build & CD %GOPATH%
CD src\shaper3 & go build & CD %GOPATH%
CD src\shaper_ans1 & go build & CD %GOPATH%
CD src\shaper_ans2 & go build & CD %GOPATH%
CD src\shaper_ans3 & go build & CD %GOPATH%
CD src\sizeimages1 & go build & CD %GOPATH%
CD src\sizeimages2 & go build & CD %GOPATH%
CD src\soundex & go build & CD %GOPATH%
CD src\stacker & go build & CD %GOPATH%
CD src\statistics & go build & CD %GOPATH%
CD src\statistics_ans & go build & CD %GOPATH%
CD src\statistics_nonstop & go build & CD %GOPATH%
CD src\statistics_nonstop2 & go build & CD %GOPATH%
CD src\wordfrequency & go build & CD %GOPATH%
CD src\unpack & go build & CD %GOPATH%
CD src\unpack_ans & go build & CD %GOPATH%
CD src\utf16-to-utf8 & go build & CD %GOPATH%
